apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacaptureservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacaptureservice
  template:
    metadata:
      labels:
        app: datacaptureservice
    spec:
      containers:
        - name: datacaptureservice
          image: datacaptureservis:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: datacaptureservice-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: datacaptureservice
  ports:
    - name: datacaptureservice
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: datacaptureservice-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: datacaptureservice
  ports:
    - name: datacaptureservice
      protocol: TCP
      port: 80
      targetPort: 80
