apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq-container
          image: datalust/seq:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: seq-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: seq-loadbalancer-service
spec:
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
