apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfoservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinfoservice
  template:
    metadata:
      labels:
        app: userinfoservice
    spec:
      containers:
        - name: userinfoservice
          image: userinfoservis:1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: userinfoservice-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: userinfoservice
  ports:
    - name: userinfoservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: userinfoservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666
---
apiVersion: v1
kind: Service
metadata:
  name: userinfoservice-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: userinfoservice
  ports:
    - name: userinfoservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: userinfoservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666
