# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: postgresql-deployment
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: postgresql
# #   template:
# #     metadata:
# #       labels:
# #         app: postgresql
# #     spec:
# #       containers:
# #         - name: postgresql
# #           image: postgres:latest
# #           ports:
# #             - containerPort: 5432
# #           envFrom:
# #             - configMapRef:
# #                 name: postgresql-credentials
# #           volumeMounts:
# #             - name: postgresql-data
# #               mountPath: /var/lib/postgresql/data
# #             - name: postgresql-init-script
# #               mountPath: /docker-entrypoint-initdb.d
# #               readOnly: true
# #       volumes:
# #         - name: postgresql-data
# #           emptyDir: {}
# #         - name: postgresql-init-script
# #           configMap:
# #             name: postgresql-volume
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: postgresql-clusterip-service
# # spec:
# #   type: ClusterIP
# #   selector:
# #     app: postgresql
# #   ports:
# #     - protocol: TCP
# #       port: 5433
# #       targetPort: 5432
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: postgresql-loadbalancer-service
# # spec:
# #   type: LoadBalancer
# #   selector:
# #     app: postgresql
# #   ports:
# #     - protocol: TCP
# #       port: 5433
# #       targetPort: 5432

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgresql-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgresql
#   template:
#     metadata:
#       labels:
#         app: postgresql
#     spec:
#       containers:
#         - name: postgresql
#           image: postgres:latest
#           ports:
#             - containerPort: 5432
#           envFrom:
#             - configMapRef:
#                 name: postgresql-credentials
#           volumeMounts:
#             - name: postgresql-data
#               mountPath: /var/lib/postgresql/data
#             - name: postgresql-init-script
#               mountPath: /docker-entrypoint-initdb.d
#               readOnly: true
#       volumes:
#         - name: postgresql-data
#           emptyDir: {}
#         - name: postgresql-init-script
#           configMap:
#             name: postgresql-volume
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgresql-clusterip-service
# spec:
#   type: ClusterIP
#   selector:
#     app: postgresql
#   ports:
#     - protocol: TCP
#       port: 5433
#       targetPort: 5432
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgresql-loadbalancer-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: postgresql
#   ports:
#     - protocol: TCP
#       port: 5433
#       targetPort: 5432

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgresql-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgresql
#   template:
#     metadata:
#       labels:
#         app: postgresql
#     spec:
#       containers:
#         - name: postgresql
#           image: postgres:latest
#           ports:
#             - containerPort: 5432
#           envFrom:
#             - configMapRef:
#                 name: postgresql-credentials
#           volumeMounts:
#             - name: postgresql-data
#               mountPath: /var/lib/postgresql/data
#             - name: postgresql-init-script
#               mountPath: /docker-entrypoint-initdb.d
#               readOnly: true
#       volumes:
#         - name: postgresql-data
#           emptyDir: {}
#         - name: postgresql-init-script
#           configMap:
#             name: postgresql-volume
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgresql-clusterip-service
# spec:
#   type: ClusterIP
#   selector:
#     app: postgresql
#   ports:
#     - protocol: TCP
#       port: 5433
#       targetPort: 5432
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgresql-loadbalancer-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: postgresql
#   ports:
#     - protocol: TCP
#       port: 5433
#       targetPort: 5432

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-credentials
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
      volumes:
        - name: postgresql-data
          emptyDir: {}
        - name: postgresql-init-script
          configMap:
            name: postgresql-volume
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
