# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: locationservice-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: locationservice
#   template:
#     metadata:
#       labels:
#         app: locationservice
#     spec:
#       containers:
#         - name: locationservice
#           image: locationservis:14.0
#           env:
#             - name: ASPNETCORE_ENVIRONMENT
#               value: "Production"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: locationservice-clusterip-service
# spec:
#   type: ClusterIP
#   selector:
#     app: locationservice
#   ports:
#     - name: locationservice
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: locationservicegrpc
#       protocol: TCP
#       port: 666
#       targetPort: 666
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: locationservice-loadbalancer-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: locationservice
#   ports:
#     - name: locationservice
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: locationservicegrpc
#       protocol: TCP
#       port: 666
#       targetPort: 666

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locationservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locationservice
  template:
    metadata:
      labels:
        app: locationservice
    spec:
      containers:
        - name: locationservice
          image: locationservis:14.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: locationservice-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: locationservice
  ports:
    - name: locationservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: locationservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666
---
apiVersion: v1
kind: Service
metadata:
  name: locationservice-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: locationservice
  ports:
    - name: locationservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: locationservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666
