# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: dataprocessservice-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: dataprocessservice
#   template:
#     metadata:
#       labels:
#         app: dataprocessservice
#     spec:
#       containers:
#         - name: dataprocessservice
#           image: dataprocessservis:16.0
#           env:
#             - name: ASPNETCORE_ENVIRONMENT
#               value: "Production"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: dataprocessservice-clusterip-service
# spec:
#   type: ClusterIP
#   selector:
#     app: dataprocessservice
#   ports:
#     - name: dataprocessservice
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: dataprocessservicegrpc
#       protocol: TCP
#       port: 666
#       targetPort: 666
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: dataprocessservice-loadbalancer-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: dataprocessservice
#   ports:
#     - name: dataprocessservice
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: dataprocessservicegrpc
#       protocol: TCP
#       port: 666
#       targetPort: 666

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataprocessservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataprocessservice
  template:
    metadata:
      labels:
        app: dataprocessservice
    spec:
      containers:
        - name: dataprocessservice
          image: dataprocessservis:16.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dataprocessservice-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: dataprocessservice
  ports:
    - name: dataprocessservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dataprocessservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666
---
apiVersion: v1
kind: Service
metadata:
  name: dataprocessservice-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: dataprocessservice
  ports:
    - name: dataprocessservice
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dataprocessservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666
