apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment.yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.9.7
          ports:
            - containerPort: 8500
            - containerPort: 8600
            - containerPort: 8600
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: consul-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: consul
  ports:
    - name: port1
      port: 8500
      targetPort: 8500
    - name: port2-tcp
      port: 8600
      targetPort: 8600
      protocol: TCP
    - name: port2-udp
      port: 8600
      targetPort: 8600
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: consul-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: consul
  ports:
    - name: port1
      port: 8500
      targetPort: 8500
    - name: port2-tcp
      port: 8600
      targetPort: 8600
      protocol: TCP
    - name: port2-udp
      port: 8600
      targetPort: 8600
      protocol: UDP
