apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientandserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientandserver
  template:
    metadata:
      labels:
        app: clientandserver
    spec:
      containers:
        - name: clientandserver
          image: clientandserverservis:3.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: clientandserver-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: clientandserver
  ports:
    - name: clientandserver
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clientandserver-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: clientandserver
  ports:
    - name: clientandserver
      protocol: TCP
      port: 80
      targetPort: 80
